CREATE VIEW USER_VIEW AS
  SELECT USERNAME, FIRST_NAME, SURNAME, REGION
  FROM USERTBL;

CREATE VIEW COMMERCIALUSER_VIEW AS
  SELECT U.USERNAME, U.FIRST_NAME, U.SURNAME, U.REGION, CU.ISPREMIUM
  FROM COMMERCIALUSER CU
  INNER JOIN USERTBL U ON CU.USERID = U.USERID;

CREATE VIEW SYSTEMUSER_VIEW AS
SELECT U.USERNAME, U.FIRST_NAME, U.SURNAME, U.REGION, SU.ISACTIVE, C.COUNTRY, C.CITY, C.PHONE
FROM USERTBL U
  INNER JOIN SYSTEMUSER SU
    ON U.USERID = SU.USERID
  INNER JOIN CONTACT C
    ON U.USERID = C.USERID;
  

CREATE VIEW AUTHOR_USERVIEW AS
  SELECT AUTHOR_NAME, AUTHOR_SUMMARY, IMAGE
  FROM AUTHOR;
  
  
CREATE VIEW AUTHOR_ADMINVIEW AS
  SELECT A.AUTHORID, A.AUTHOR_NAME, 
         A.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER, 
         A.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM AUTHOR A
  INNER JOIN USERTBL U1 ON U1.USERID = A.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = A.LAST_UPDATE_USER;


CREATE VIEW BOOK_USERVIEW AS
  SELECT BOOKNAME, BOOK_SUMMARY, COVER_IMAGE 
  FROM BOOK;  

CREATE VIEW BOOK_ADMINVIEW AS
  SELECT B.BOOKID, B.BOOKNAME, 
         B.INSERT_USER INSERTUERID, U1.USERNAME INSERTUSER,
         B.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM BOOK B
  INNER JOIN USERTBL U1 ON U1.USERID = B.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = B.LAST_UPDATE_USER;


CREATE VIEW PUBLISHER_USERVIEW AS
  SELECT PUBLISHER_NAME, PUBLISHER_SUMMARY
  FROM PUBLISHER;  

CREATE VIEW PUBLISHER_ADMINVIEW AS
  SELECT P.PUBLISHERID, P.PUBLISHER_NAME,
         P.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         P.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM PUBLISHER P
  INNER JOIN USERTBL U1 ON U1.USERID = P.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = P.LAST_UPDATE_USER
  ORDER BY P.PUBLISHERID ASC;
  
  
CREATE VIEW CATEGORY_ADMINVIEW AS
  SELECT C.CATEGORYID, C.CATEGORY_NAME,
         C.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         C.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM CATEGORYTBL C
  INNER JOIN USERTBL U1 ON U1.USERID = C.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = C.LAST_UPDATE_USER
  ORDER BY C.CATEGORYID; 
  
  
CREATE VIEW FILE_ADMINVIEW AS
  SELECT F.FILEID, B.BOOKNAME, P.PUBLISHERID, P.PUBLISHER_NAME PUBLISHER,
         F.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         F.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM FILETBL F
  INNER JOIN USERTBL U1 ON U1.USERID = F.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = F.LAST_UPDATE_USER
  INNER JOIN BOOK B ON B.BOOKID = F.BOOKID
  INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
  ORDER BY F.FILEID;
  
CREATE VIEW EBOOK_VIEW AS
  SELECT B.BOOKNAME, P.PUBLISHER_NAME PUBLISHER, F.PUBLISH_DATE, F.PAGE_NUMBER, E.EBOOK_FILE
  FROM EBOOK E
    INNER JOIN FILETBL F ON E.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
    ORDER BY F.FILEID;
    

CREATE VIEW AUDIOBOOK_VIEW AS
  SELECT B.BOOKNAME, P.PUBLISHER_NAME PUBLISHER, F.PUBLISH_DATE, F.PAGE_NUMBER, 
         A.AUDIO_FILE, A.TOTAL_DURATION
  FROM AUDIOBOOK A
    INNER JOIN FILETBL F ON A.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
    ORDER BY F.FILEID;
    

CREATE VIEW USER_BOOKNUMBER_VIEW AS
  SELECT COUNT(FILEID) AS FILENUMBER, USERID
  FROM LIBRARYTBL
  GROUP BY USERID;
  
  
CREATE VIEW AUTHOR_BOOKNUMBER_VIEW AS
  SELECT AUTHOR.AUTHOR_NAME, COUNT(BOOKAUTHOR.BOOKID) AS BOOKNUMBER
    FROM AUTHOR, BOOKAUTHOR
    WHERE AUTHOR.AUTHORID = BOOKAUTHOR.AUTHORID
    GROUP BY AUTHOR.AUTHOR_NAME
    ORDER BY BOOKNUMBER DESC;
    
CREATE VIEW CATEGORY_BOOKNUMBER_VIEW AS
  SELECT CATEGORYTBL.CATEGORY_NAME, COUNT(BOOKCATEGORY.BOOKID) AS BOOKNUMBER
  FROM BOOKCATEGORY, CATEGORYTBL
  WHERE BOOKCATEGORY.CATEGORYID = CATEGORYTBL.CATEGORYID
  GROUP BY CATEGORYTBL.CATEGORY_NAME
  ORDER BY BOOKNUMBER DESC;

CREATE VIEW BOOK_ADDINGNUMBER_VIEW AS
  SELECT B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN FILETBL F ON L.FILEID = F.FILEID
    INNER JOIN BOOK B    ON F.BOOKID = B.BOOKID
    GROUP BY B.BOOKNAME
    ORDER BY USERNUMBER DESC;
    
CREATE VIEW FILE_ADDINGNUMBER_VIEW AS
  SELECT F.FILEID, B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN FILETBL F ON L.FILEID = F.FILEID
    INNER JOIN BOOK B    ON F.BOOKID = B.BOOKID
    GROUP BY F.FILEID, B.BOOKNAME
    ORDER BY USERNUMBER DESC;
    
CREATE VIEW EBOOK_ADDINGNUMBER_VIEW AS
  SELECT E.FILEID, B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN EBOOK E ON L.FILEID = E.FILEID
    INNER JOIN FILETBL F ON E.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY E.FILEID, B.BOOKNAME
    ORDER BY USERNUMBER DESC;


CREATE VIEW AUDIOBOOK_ADDINGNUMBER_VIEW AS
  SELECT A.FILEID, B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN AUDIOBOOK A ON L.FILEID = A.FILEID
    INNER JOIN FILETBL F ON A.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY A.FILEID, B.BOOKNAME
    ORDER BY USERNUMBER DESC;
    
CREATE VIEW LANGUAGE_BOOKNUMBER_VIEW AS
  SELECT F.FILE_LANGUAGE BOOK_LANGUAGE, COUNT(F.FILEID) BOOK_NUMBER
  FROM FILETBL F
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY F.FILE_LANGUAGE
    ORDER BY BOOK_NUMBER DESC;

  