--------------------------------------------------------
--  File created - Perþembe-Mayýs-25-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View AUDIOBOOK_ADDINGNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUDIOBOOK_ADDINGNUMBER_VIEW" ("FILEID", "BOOKNAME", "USERNUMBER") AS 
  SELECT A.FILEID, B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN AUDIOBOOK A ON L.FILEID = A.FILEID
    INNER JOIN FILETBL F ON A.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY A.FILEID, B.BOOKNAME
    ORDER BY USERNUMBER DESC
;
--------------------------------------------------------
--  DDL for View AUDIOBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUDIOBOOK_VIEW" ("FILEID", "FILE_SIZE", "FILE_LANGUAGE", "BOOKID", "BOOKNAME", "PUBLISHERID", "PUBLISHER", "PUBLISH_DATE", "PAGE_NUMBER", "AUDIO_FILE", "TOTAL_DURATION") AS 
  SELECT F.FILEID, F.FILE_SIZE, F.FILE_LANGUAGE, B.BOOKID, B.BOOKNAME, P.PUBLISHERID, P.PUBLISHER_NAME PUBLISHER, 
    F.PUBLISH_DATE, F.PAGE_NUMBER, A.AUDIO_FILE, A.TOTAL_DURATION
    FROM AUDIOBOOK A
      INNER JOIN FILETBL F ON A.FILEID = F.FILEID
      INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
      INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
    ORDER BY B.BOOKNAME
;
--------------------------------------------------------
--  DDL for View AUTHOR_ADMINVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUTHOR_ADMINVIEW" ("AUTHORID", "AUTHOR_NAME", "INSERTUSERID", "INSERTUSER", "LASTUPDATEUSERID", "LASTUPDATEUSER") AS 
  SELECT A.AUTHORID, A.AUTHOR_NAME, 
         A.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER, 
         A.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM AUTHOR A
  INNER JOIN USERTBL U1 ON U1.USERID = A.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = A.LAST_UPDATE_USER
;
--------------------------------------------------------
--  DDL for View AUTHOR_BOOKNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUTHOR_BOOKNUMBER_VIEW" ("AUTHOR_NAME", "BOOKNUMBER") AS 
  SELECT AUTHOR.AUTHOR_NAME, COUNT(BOOKAUTHOR.BOOKID) AS BOOKNUMBER
    FROM AUTHOR, BOOKAUTHOR
    WHERE AUTHOR.AUTHORID = BOOKAUTHOR.AUTHORID
    GROUP BY AUTHOR.AUTHOR_NAME
    ORDER BY BOOKNUMBER DESC
;
--------------------------------------------------------
--  DDL for View AUTHOR_MOSTLIBRARY_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUTHOR_MOSTLIBRARY_VIEW" ("AUTHORID", "AUTHOR_NAME", "IMAGE", "USERNUMBER") AS 
  SELECT A.AUTHORID, A.AUTHOR_NAME, A.IMAGE, COUNT(L.USERID) USERNUMBER
    FROM AUTHOR A
    INNER JOIN BOOKAUTHOR BA ON A.AUTHORID = BA.AUTHORID
    INNER JOIN BOOK B ON BA.BOOKID = B.BOOKID
    INNER JOIN FILETBL F ON F.BOOKID = B.BOOKID
    INNER JOIN LIBRARYTBL L ON L.FILEID = F.FILEID
    GROUP BY A.AUTHORID, A.AUTHOR_NAME, A.IMAGE
    ORDER BY USERNUMBER DESC
;
--------------------------------------------------------
--  DDL for View AUTHOR_USERVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "AUTHOR_USERVIEW" ("AUTHOR_NAME", "AUTHOR_SUMMARY", "IMAGE") AS 
  SELECT AUTHOR_NAME, AUTHOR_SUMMARY, IMAGE
  FROM AUTHOR
;
--------------------------------------------------------
--  DDL for View BOOK_ADDINGNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "BOOK_ADDINGNUMBER_VIEW" ("BOOKID", "BOOKNAME", "COVER_IMAGE", "USERNUMBER") AS 
  SELECT B.BOOKID, B.BOOKNAME, B.COVER_IMAGE, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN FILETBL F ON L.FILEID = F.FILEID
    INNER JOIN BOOK B    ON F.BOOKID = B.BOOKID
    GROUP BY B.BOOKID, B.BOOKNAME, B.COVER_IMAGE
    ORDER BY USERNUMBER DESC
;
--------------------------------------------------------
--  DDL for View BOOK_ADMINVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "BOOK_ADMINVIEW" ("BOOKID", "BOOKNAME", "INSERTUERID", "INSERTUSER", "LASTUPDATEUSERID", "LASTUPDATEUSER") AS 
  SELECT B.BOOKID, B.BOOKNAME, 
         B.INSERT_USER INSERTUERID, U1.USERNAME INSERTUSER,
         B.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM BOOK B
  INNER JOIN USERTBL U1 ON U1.USERID = B.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = B.LAST_UPDATE_USER
;
--------------------------------------------------------
--  DDL for View BOOKAUTHOR_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "BOOKAUTHOR_VIEW" ("BOOKID", "BOOKNAME", "AUTHORID", "AUTHOR_NAME") AS 
  SELECT B.BOOKID, B.BOOKNAME, A.AUTHORID, A.AUTHOR_NAME
    FROM BOOK B
    INNER JOIN BOOKAUTHOR BA ON B.BOOKID = BA.BOOKID
    INNER JOIN AUTHOR A ON BA.AUTHORID = A.AUTHORID
;
--------------------------------------------------------
--  DDL for View BOOKCATEGORY_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "BOOKCATEGORY_VIEW" ("BOOKID", "BOOKNAME", "CATEGORYID", "CATEGORY_NAME") AS 
  SELECT B.BOOKID, B.BOOKNAME,C.CATEGORYID, C.CATEGORY_NAME
    FROM BOOK B
    INNER JOIN BOOKCATEGORY BC ON B.BOOKID = BC.BOOKID
    INNER JOIN CATEGORYTBL C ON C.CATEGORYID = BC.CATEGORYID
;
--------------------------------------------------------
--  DDL for View BOOK_USERVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "BOOK_USERVIEW" ("BOOKID", "BOOKNAME", "BOOK_SUMMARY", "COVER_IMAGE") AS 
  SELECT BOOKID, BOOKNAME, BOOK_SUMMARY, COVER_IMAGE 
  FROM BOOK
;
--------------------------------------------------------
--  DDL for View CATEGORY_ADMINVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "CATEGORY_ADMINVIEW" ("CATEGORYID", "CATEGORY_NAME", "INSERTUSERID", "INSERTUSER", "LASTUPDATEUSERID", "LASTUPDATEUSER") AS 
  SELECT C.CATEGORYID, C.CATEGORY_NAME,
         C.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         C.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM CATEGORYTBL C
  INNER JOIN USERTBL U1 ON U1.USERID = C.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = C.LAST_UPDATE_USER
  ORDER BY C.CATEGORYID
;
--------------------------------------------------------
--  DDL for View CATEGORY_BOOKNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "CATEGORY_BOOKNUMBER_VIEW" ("CATEGORY_NAME", "BOOKNUMBER") AS 
  SELECT CATEGORYTBL.CATEGORY_NAME, COUNT(BOOKCATEGORY.BOOKID) AS BOOKNUMBER
  FROM BOOKCATEGORY, CATEGORYTBL
  WHERE BOOKCATEGORY.CATEGORYID = CATEGORYTBL.CATEGORYID
  GROUP BY CATEGORYTBL.CATEGORY_NAME
  ORDER BY BOOKNUMBER DESC
;
--------------------------------------------------------
--  DDL for View CATEGORYINHERITANCE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "CATEGORYINHERITANCE_VIEW" ("PARENTID", "PARENT_NAME", "SUBID", "SUB_NAME") AS 
  SELECT CP.CATEGORYID PARENTID, CP.CATEGORY_NAME PARENT_NAME, CS.CATEGORYID SUBID, CS.CATEGORY_NAME SUB_NAME
    FROM CATEGORYINHERITANCE CI
    INNER JOIN CATEGORYTBL  CP ON CP.CATEGORYID = CI.PARENT_CATEGORYID
    INNER JOIN CATEGORYTBL CS ON CS.CATEGORYID = CI.SUBCATEGORYID
;
--------------------------------------------------------
--  DDL for View COMMERCIALUSER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COMMERCIALUSER_VIEW" ("USERNAME", "FIRST_NAME", "SURNAME", "REGION", "ISPREMIUM") AS 
  SELECT U.USERNAME, U.FIRST_NAME, U.SURNAME, U.REGION, CU.ISPREMIUM
  FROM COMMERCIALUSER CU
  INNER JOIN USERTBL U ON CU.USERID = U.USERID
;
--------------------------------------------------------
--  DDL for View EBOOK_ADDINGNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "EBOOK_ADDINGNUMBER_VIEW" ("FILEID", "BOOKNAME", "COVER_IMAGE", "USERNUMBER") AS 
  SELECT E.FILEID, B.BOOKNAME, B.COVER_IMAGE, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN EBOOK E ON L.FILEID = E.FILEID
    INNER JOIN FILETBL F ON E.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY E.FILEID, B.BOOKNAME, B.COVER_IMAGE
    ORDER BY USERNUMBER DESC
;
--------------------------------------------------------
--  DDL for View EBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "EBOOK_VIEW" ("FILEID", "FILE_SIZE", "FILE_LANGUAGE", "BOOKID", "BOOKNAME", "PUBLISHERID", "PUBLISHER", "PUBLISH_DATE", "PAGE_NUMBER", "EBOOK_FILE") AS 
  SELECT F.FILEID, F.FILE_SIZE, F.FILE_LANGUAGE, B.BOOKID, B.BOOKNAME, P.PUBLISHERID, P.PUBLISHER_NAME PUBLISHER, F.PUBLISH_DATE, F.PAGE_NUMBER, E.EBOOK_FILE
  FROM EBOOK E
    INNER JOIN FILETBL F ON E.FILEID = F.FILEID
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
    ORDER BY B.BOOKNAME
;
--------------------------------------------------------
--  DDL for View FICTION_BOOKS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "FICTION_BOOKS" ("BOOKNAME", "COVER_IMAGE") AS 
  SELECT b.BOOKNAME, b.COVER_IMAGE
  from BOOK b
  inner join BOOKCATEGORY bc on bc.BOOKID = b.BOOKID
  inner join CATEGORYTBL c on bc.CATEGORYID = c.CATEGORYID
  where c.CATEGORY_NAME = 'FICTION'
;
--------------------------------------------------------
--  DDL for View FICTION_BOOKS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "FICTION_BOOKS_VIEW" ("BOOKNAME", "COVER_IMAGE") AS 
  SELECT b.BOOKNAME, b.COVER_IMAGE
  from BOOK b
  inner join BOOKCATEGORY bc on bc.BOOKID = b.BOOKID
  inner join CATEGORYTBL c on bc.CATEGORYID = c.CATEGORYID
  where c.CATEGORY_NAME = 'FICTION'
;
--------------------------------------------------------
--  DDL for View FILE_ADDINGNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "FILE_ADDINGNUMBER_VIEW" ("FILEID", "BOOKNAME", "USERNUMBER") AS 
  SELECT F.FILEID, B.BOOKNAME, COUNT(L.USERID) USERNUMBER
  FROM LIBRARYTBL L
    INNER JOIN USERTBL U ON L.USERID = U.USERID
    INNER JOIN FILETBL F ON L.FILEID = F.FILEID
    INNER JOIN BOOK B    ON F.BOOKID = B.BOOKID
    GROUP BY F.FILEID, B.BOOKNAME
    ORDER BY USERNUMBER DESC
;
--------------------------------------------------------
--  DDL for View FILE_ADMINVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "FILE_ADMINVIEW" ("FILEID", "BOOKID", "BOOKNAME", "PUBLISHERID", "PUBLISHER", "INSERTUSERID", "INSERTUSER", "LASTUPDATEUSERID", "LASTUPDATEUSER") AS 
  SELECT F.FILEID, B.BOOKID, B.BOOKNAME, P.PUBLISHERID, P.PUBLISHER_NAME PUBLISHER,
         F.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         F.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
    FROM FILETBL F
    INNER JOIN USERTBL U1 ON U1.USERID = F.INSERT_USER
    INNER JOIN USERTBL U2 ON U2.USERID = F.LAST_UPDATE_USER
    INNER JOIN BOOK B ON B.BOOKID = F.BOOKID
    INNER JOIN PUBLISHER P ON P.PUBLISHERID = F.PUBLISHERID
    ORDER BY F.FILEID
;
--------------------------------------------------------
--  DDL for View HAVE_MOST_BOOKS_USER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "HAVE_MOST_BOOKS_USER_VIEW" ("FILENUMBER", "USERNAME") AS 
  SELECT T.FILENUMBER, T.USERNAME FROM
(
  SELECT COUNT(FILEID) AS FILENUMBER, U.USERID, U.USERNAME, LT.USERID
  FROM LIBRARYTBL LT
  INNER JOIN USERTBL U ON LT.USERID = U.USERID 
  GROUP BY U.USERID, U.USERNAME, LT.USERID
  ORDER BY FILENUMBER DESC
) T
FETCH FIRST 1 ROWS ONLY
;
--------------------------------------------------------
--  DDL for View LANGUAGE_BOOKNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "LANGUAGE_BOOKNUMBER_VIEW" ("BOOK_LANGUAGE", "BOOK_NUMBER") AS 
  SELECT F.FILE_LANGUAGE BOOK_LANGUAGE, COUNT(F.FILEID) BOOK_NUMBER
  FROM FILETBL F
    INNER JOIN BOOK B ON F.BOOKID = B.BOOKID
    GROUP BY F.FILE_LANGUAGE
    ORDER BY BOOK_NUMBER DESC
;
--------------------------------------------------------
--  DDL for View LIBRARY_AUDIOBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "LIBRARY_AUDIOBOOK_VIEW" ("USERID", "BOOKID", "BOOKNAME", "FILEID", "PUBLISHERID", "PUBLISHER_NAME", "PUBLISH_DATE", "TOTAL_DURATION") AS 
  SELECT l.USERID, l.BOOKID, l.BOOKNAME, l.FILEID, l.PUBLISHERID, l.PUBLISHER_NAME, 
           a.PUBLISH_DATE, a.TOTAL_DURATION
    FROM USER_LIBRARY_VIEW l
    INNER JOIN AUDIOBOOK_VIEW a ON a.FILEID = l.FILEID
;
--------------------------------------------------------
--  DDL for View LIBRARY_EBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "LIBRARY_EBOOK_VIEW" ("USERID", "BOOKID", "BOOKNAME", "FILEID", "PUBLISHERID", "PUBLISHER_NAME", "PUBLISH_DATE", "PAGE_NUMBER") AS 
  SELECT l.USERID, l.BOOKID, l.BOOKNAME, l.FILEID, l.PUBLISHERID, l.PUBLISHER_NAME, 
           a.PUBLISH_DATE, a.PAGE_NUMBER
    FROM USER_LIBRARY_VIEW l
    INNER JOIN EBOOK_VIEW a ON a.FILEID = l.FILEID
;
--------------------------------------------------------
--  DDL for View PARENTCATEGORY_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "PARENTCATEGORY_VIEW" ("CATEGORYID", "CATEGORY_NAME", "INSERT_USER", "LAST_UPDATE_USER", "INSERT_DATE", "LAST_UPDATE_DATE") AS 
  SELECT "CATEGORYID","CATEGORY_NAME","INSERT_USER","LAST_UPDATE_USER","INSERT_DATE","LAST_UPDATE_DATE" 
    FROM CATEGORYTBL C
    WHERE NOT EXISTS (SELECT NULL
                      FROM CATEGORYINHERITANCE CI
                      WHERE CI.SUBCATEGORYID = C.CATEGORYID
                      )
;
--------------------------------------------------------
--  DDL for View PUBLISHER_ADMINVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "PUBLISHER_ADMINVIEW" ("PUBLISHERID", "PUBLISHER_NAME", "INSERTUSERID", "INSERTUSER", "LASTUPDATEUSERID", "LASTUPDATEUSER") AS 
  SELECT P.PUBLISHERID, P.PUBLISHER_NAME,
         P.INSERT_USER INSERTUSERID, U1.USERNAME INSERTUSER,
         P.LAST_UPDATE_USER LASTUPDATEUSERID, U2.USERNAME LASTUPDATEUSER
  FROM PUBLISHER P
  INNER JOIN USERTBL U1 ON U1.USERID = P.INSERT_USER
  INNER JOIN USERTBL U2 ON U2.USERID = P.LAST_UPDATE_USER
  ORDER BY P.PUBLISHERID ASC
;
--------------------------------------------------------
--  DDL for View PUBLISHER_USERVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "PUBLISHER_USERVIEW" ("PUBLISHER_NAME", "PUBLISHER_SUMMARY") AS 
  SELECT PUBLISHER_NAME, PUBLISHER_SUMMARY
  FROM PUBLISHER
;
--------------------------------------------------------
--  DDL for View PUBLISHER_WITHMOSTPUBLISH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "PUBLISHER_WITHMOSTPUBLISH" ("PUBLISHERID", "PUBLISHER_NAME", "COUNT") AS 
  SELECT
    FILETBL.PUBLISHERID,
    PUBLISHER.PUBLISHER_NAME,
    count(*) COUNT
  FROM PUBLISHER
    INNER JOIN FILETBL ON FILETBL.PUBLISHERID = PUBLISHER.PUBLISHERID
  GROUP BY FILETBL.PUBLISHERID, PUBLISHER.PUBLISHER_NAME
  ORDER BY COUNT DESC
;
--------------------------------------------------------
--  DDL for View SHELF_AUDIOBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SHELF_AUDIOBOOK_VIEW" ("USERID", "BOOKID", "BOOKNAME", "FILEID", "PUBLISHERID", "PUBLISHER_NAME", "SHELFID", "SHELFNAME", "PUBLISH_DATE", "TOTAL_DURATION") AS 
  SELECT s.USERID, s.BOOKID, s.BOOKNAME, s.FILEID, s.PUBLISHERID, s.PUBLISHER_NAME, 
           s.SHELFID SHELFID, s.SHELFNAME, a.PUBLISH_DATE, a.TOTAL_DURATION
    FROM USER_SHELF_VIEW s
    INNER JOIN AUDIOBOOK_VIEW a ON s.FILEID = a.FILEID
;
--------------------------------------------------------
--  DDL for View SHELF_EBOOK_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SHELF_EBOOK_VIEW" ("USERID", "BOOKID", "BOOKNAME", "FILEID", "PUBLISHERID", "PUBLISHER_NAME", "SHELFID", "SHELFNAME", "PUBLISH_DATE", "PAGE_NUMBER") AS 
  SELECT s.USERID, s.BOOKID, s.BOOKNAME, s.FILEID, s.PUBLISHERID, s.PUBLISHER_NAME, 
           s.SHELFID SHELFID, s.SHELFNAME, e.PUBLISH_DATE, e.PAGE_NUMBER PAGE_NUMBER
    FROM USER_SHELF_VIEW s
    INNER JOIN EBOOK_VIEW e ON e.FILEID = s.FILEID
;
--------------------------------------------------------
--  DDL for View SYSTEMUSER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SYSTEMUSER_VIEW" ("USERID", "USERNAME", "FIRST_NAME", "SURNAME", "REGION", "ISACTIVE", "COUNTRY", "CITY", "PHONE") AS 
  SELECT U.USERID, U.USERNAME, U.FIRST_NAME, U.SURNAME, U.REGION, SU.ISACTIVE, C.COUNTRY, C.CITY, C.PHONE
FROM USERTBL U
  INNER JOIN SYSTEMUSER SU
    ON U.USERID = SU.USERID
  INNER JOIN CONTACT C
    ON U.USERID = C.USERID
;
--------------------------------------------------------
--  DDL for View USER_BOOKNUMBER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "USER_BOOKNUMBER_VIEW" ("FILENUMBER", "USERID") AS 
  SELECT COUNT(FILEID) AS FILENUMBER, USERID
  FROM LIBRARYTBL
  GROUP BY USERID
;
--------------------------------------------------------
--  DDL for View USER_LIBRARY_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "USER_LIBRARY_VIEW" ("BOOKID", "BOOKNAME", "USERID", "FILEID", "PUBLISHERID", "PUBLISHER_NAME") AS 
  SELECT b.BOOKID, b.BOOKNAME, u.USERID, ft.fileid, p.PUBLISHERID, p.PUBLISHER_NAME
    FROM USERTBL u
    INNER JOIN LIBRARYTBL lt ON u.userid = lt.userid
    INNER JOIN FILETBL ft ON ft.FILEID = lt.FILEID
    INNER JOIN BOOK b ON b.BOOKID = ft.BOOKID
    INNER JOIN Publisher p ON ft.PUBLISHERID = p.PUBLISHERID
    WHERE ft.BOOKID = b.BOOKID AND ft.PUBLISHERID = p.PUBLISHERID
;
--------------------------------------------------------
--  DDL for View USER_SHELF_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "USER_SHELF_VIEW" ("USERID", "BOOKID", "BOOKNAME", "FILEID", "PUBLISHERID", "PUBLISHER_NAME", "SHELFNAME", "SHELFID") AS 
  SELECT u.USERID, b.BOOKID, b.BOOKNAME,ft.FILEID, p.PUBLISHERID, p.PUBLISHER_NAME, s.SHELFNAME, s.SHELFID
  FROM USERTBL u
  INNER JOIN SHELF s on u.USERID = s.USERID
  INNER JOIN SHELFFILE sf on s.SHELFID = sf.SHELFID
  INNER JOIN FILETBL ft ON sf.FILEID = ft.FILEID
  INNER JOIN BOOK b ON b.BOOKID = ft.BOOKID
  INNER JOIN PUBLISHER p on ft.PUBLISHERID = p.PUBLISHERID
;
--------------------------------------------------------
--  DDL for View USER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "USER_VIEW" ("USERNAME", "FIRST_NAME", "SURNAME", "REGION") AS 
  SELECT USERNAME, FIRST_NAME, SURNAME, REGION
  FROM USERTBL
;
--------------------------------------------------------
--  DDL for View USER_WITHMOSTSHELF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "USER_WITHMOSTSHELF" ("USERID", "USERNAME", "COUNT") AS 
  SELECT
  SHELF.USERID,
  USERTBL.USERNAME,
  COUNT(*) COUNT
FROM SHELF
  INNER JOIN USERTBL ON SHELF.USERID = USERTBL.USERID
GROUP BY SHELF.USERID, USERTBL.USERNAME
ORDER BY COUNT DESC
;
